services:
  backend:
    image: {{backend}}
    container_name: my-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    image: {{frontend}}
    container_name: my-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
