services:
  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "8000:8000"        # Maps host 8000 → container 8000
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: my-frontend
    ports:
      - "3000:3000"        # Maps host 3000 → container 3000
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
