apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ACR_URL}}/frontend:latest"  # Changed from ${ACR_URL} to {{ACR_URL}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BASE_URL
              value: "http://$(POD_IP):30080"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
