apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "${ACR_URL}/frontend:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BASE_URL
              value: "http://$(POD_IP):30080"  # Kubernetes will resolve POD_IP dynamically
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP  # The fieldPath points to the pod's IP address
